# Generated by Django 3.1.6 on 2021-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsApp', '0004_auto_20210205_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_review',
            name='title',
            field=models.CharField(default='제목없음', max_length=45),
        ),
        migrations.AddField(
            model_name='testsite_review',
            name='title',
            field=models.CharField(default='제목없음', max_length=45),
        ),
    ]
